project:
  type: book
  output-dir: docs

book:
  reader-mode: true
  page-navigation: true
  title: "Dans quel étage R ?"
  subtitle: "Ou comment R envisage l'espace et le temps"
  author: 
    - name: "Alain CORVISIER"
      email: alain.corvisier@chapelier-fou.fr
  date: today
  sidebar: 
    style: floating
  repo-url: https://github.com/a-lambda/howRu/
  repo-actions: [edit]
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    - href: prerequis.qmd
      text: Prérequis
    - part: "Premier contact"
      chapters: 
        - structure/01_sf.qmd
    - part: "Digressions"
      chapters: 
        - structure/99_errements.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    cover-image: https://www.palais-decouverte.fr/fileadmin/fileadmin_Palais/fichiersContribs/au-programme/lasciencestla/H1_hasard_maths_Alain.jpg
    #images/H1_hasard_maths_Alain.jpg
    theme: 
      light: 
        - cosmo
        - css/fira-code.css
        - css/light.css
      dark:
        - slate
        - css/dark.css
    #code-fold: true
    code-link: true
    #code-tools: true
    toc: true
    #fontsize: 1.25rem
    monofont: Fira Code
    #page-layout: full
    number-depth: 2
    #css: css/styles.css
  pdf:
    documentclass: scrreprt



