project:
  type: book
  output-dir: docs

book:
  reader-mode: true
  page-navigation: true
  title: "Dans quel étage R ?"
  subtitle: "Ou comment R envisage l'espace et le temps"
  author: 
    - name: "Alain CORVISIER"
      email: alain.corvisier@chapelier-fou.fr
  date: today
  sidebar: 
    style: floating
  repo-url: https://github.com/a-lambda/howRu/
  repo-actions: [edit]
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: structure/espace.qmd
      chapters: 
        - structure/espace/contexte.qmd
    - part: structure/temps.qmd
      chapters: 
        - structure/temps/contexte.qmd
    - part: structure/divers.qmd
      chapters: 
        - structure/divers/errements.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    cover-image: images/H1_hasard_maths_Alain.jpg
    theme: 
      light: 
        - cosmo
        - css/fira-code.css
        - css/light.css
      dark:
        - slate
        - css/dark.css
    #code-fold: true
    code-link: true
    #code-tools: true
    toc: true
    #fontsize: 1.25rem
    monofont: Fira Code
    #page-layout: full
    number-depth: 1
    #css: css/styles.css
    
  pdf:
    documentclass: scrreprt



