# Introduction {.unnumbered}

Je vais tenter de regrouper dans les pages qui vont suivre l'ensemble des informations que je juge pertinente concernant le domaine des statistiques associées aux données temporelles et géospatiales. <br>

Je le fais en français parce je juge que des lacunes sont flagrantes concernant les ouvrages de ce type utilisant cette langue. <br>

Petit bémol sur cette dernière remarque. Il serait en effet dangereux, dans le cadre d'un apprentissage, de vouloir traduire l'intégralité des termes techniques, d'origine anglaise pour la majorité. Ce serait même contre-productif, car cette nomenclature métier répond d'abord à des normes internationales.  <br>

Dernière remarque, cet ouvrage se constituera de manière cahotique et ne pourra jamais faire figure, dans un premier temps, de texte de référence. Il s'agit de prime abord plutôt d'un essai qui deviendra, au cours des mois qui vont suivre, utile et légitime, ou pas du tout. <br>

Donc aucune prétention à venir ...



